/* File: memsubsmodule.c
 * This file is auto-generated with f2py (version:2_3198).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Sun Oct 29 08:43:41 2006
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *memsubs_error;
static PyObject *memsubs_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_CALGCH_in_MEMONEIT__user__routines_typedef)(int *,float *,float *,float *,float *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"memsubs.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define pyobj_from_float1(v) (PyFloat_FromDouble(v))
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    PyErr_SetString(memsubs_error,"("tcheck") failed for "name);\
    fprintf(stderr,show"\n",var);\
    /*goto capi_fail;*/\
  } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = memsubs_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (PyCObject_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":fun->ob_type->tp_name));
goto capi_fail;
}
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
  if (PyObject_HasAttrString(tmp_fun,"func_defaults"))
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(memsubs_error,errmess);
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = memsubs_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(MEMONEIT,MEMONEIT)(int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,cb_CALGCH_in_MEMONEIT__user__routines_typedef);
extern void F_FUNC(MEMCALHF,MEMCALHF)(int*,float*,float*,float*,float*,float*);
extern void F_FUNC(MEMCHALB,MEMCHALB)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*);
extern void F_FUNC(MEMCLSTP,MEMCLSTP)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*,float*);
extern void F_FUNC(MEMGDS,MEMGDS)(int*,float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(MEMINIAB,MEMINIAB)(double*,float*,float*,float*);
extern void F_FUNC(MEMTAKST,MEMTAKST)(int*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(MEMUPDAT,MEMUPDAT)(double*,float*,float*,float*,float*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************* cb_CALGCH_in_MEMONEIT__user__routines *******************/
PyObject *cb_CALGCH_in_MEMONEIT__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_CALGCH_in_MEMONEIT__user__routines_args_capi = NULL;
int cb_CALGCH_in_MEMONEIT__user__routines_nofargs = 0;
jmp_buf cb_CALGCH_in_MEMONEIT__user__routines_jmpbuf;
/*typedef void(*cb_CALGCH_in_MEMONEIT__user__routines_typedef)(int *,float *,float *,float *,float *);*/
static void cb_CALGCH_in_MEMONEIT__user__routines (int *IMSZ_cb_capi,float *MEM,float *WT,float *GCH,float *CHISQ_cb_capi) {
  PyTupleObject *capi_arglist = cb_CALGCH_in_MEMONEIT__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int IMSZ=(*IMSZ_cb_capi);
  float CHISQ=(*CHISQ_cb_capi);
  npy_intp WT_Dims[1] = {-1};
  npy_intp GCH_Dims[1] = {-1};
  npy_intp MEM_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_CALGCH_in_MEMONEIT__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_CALGCH_in_MEMONEIT__user__routines_capi=",cb_CALGCH_in_MEMONEIT__user__routines_capi);
  if (cb_CALGCH_in_MEMONEIT__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_CALGCH_in_MEMONEIT__user__routines_capi = PyObject_GetAttrString(memsubs_module,"CALGCH");
  }
  if (cb_CALGCH_in_MEMONEIT__user__routines_capi==NULL) {
    PyErr_SetString(memsubs_error,"cb: Callback CALGCH not defined (as an argument or module memsubs attribute).\n");
    goto capi_fail;
  }
  if (PyCObject_Check(cb_CALGCH_in_MEMONEIT__user__routines_capi)) {
  cb_CALGCH_in_MEMONEIT__user__routines_typedef cb_CALGCH_in_MEMONEIT__user__routines_cptr;
  cb_CALGCH_in_MEMONEIT__user__routines_cptr = PyCObject_AsVoidPtr(cb_CALGCH_in_MEMONEIT__user__routines_capi);
  (*cb_CALGCH_in_MEMONEIT__user__routines_cptr)(IMSZ_cb_capi,MEM,WT,GCH,CHISQ_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(memsubs_module,"CALGCH_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(memsubs_error,"Failed to convert memsubs.CALGCH_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(memsubs_error,"Callback CALGCH argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  ;
  ;
  ;
/*pyobjfrom*/
  if (cb_CALGCH_in_MEMONEIT__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(IMSZ)))
      goto capi_fail;
  if (cb_CALGCH_in_MEMONEIT__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,MEM_Dims,PyArray_FLOAT,NULL,(char*)MEM,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_CALGCH_in_MEMONEIT__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,WT_Dims,PyArray_FLOAT,NULL,(char*)WT,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_CALGCH_in_MEMONEIT__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,GCH_Dims,PyArray_FLOAT,NULL,(char*)GCH,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_CALGCH_in_MEMONEIT__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_float1(CHISQ)))
      goto capi_fail;
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function CALGCH.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_CALGCH_in_MEMONEIT__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_CALGCH_in_MEMONEIT__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_CALGCH_in_MEMONEIT__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_CALGCH_in_MEMONEIT__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/**************** end of cb_CALGCH_in_MEMONEIT__user__routines ****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** MEMONEIT **********************************/
static char doc_f2py_rout_memsubs_MEMONEIT[] = "\
Function signature:\n\
  MEMONEIT(DOINIT,IMSZ,MEM,DEF,DEFLEV,STP,GCH,WT,Q,TFLUX,TCHISQ,TOL,FLUX,CHISQ,ENTRPY,NRMGRD,CALGCH,[CALGCH_extra_args])\n\
Required arguments:\n"
"  DOINIT : input int\n"
"  IMSZ : input int\n"
"  MEM : input rank-1 array('f') with bounds (*)\n"
"  DEF : input rank-1 array('f') with bounds (*)\n"
"  DEFLEV : input float\n"
"  STP : input rank-1 array('f') with bounds (*)\n"
"  GCH : input rank-1 array('f') with bounds (*)\n"
"  WT : input rank-1 array('f') with bounds (*)\n"
"  Q : input float\n"
"  TFLUX : input float\n"
"  TCHISQ : input float\n"
"  TOL : input float\n"
"  FLUX : input float\n"
"  CHISQ : input float\n"
"  ENTRPY : input float\n"
"  NRMGRD : input float\n"
"  CALGCH : call-back function\n"
"Optional arguments:\n"
"  CALGCH_extra_args := () input tuple\n"
"Call-back functions:\n"
"  def CALGCH(IMSZ,MEM,WT,GCH,CHISQ): return \n\
  Required arguments:\n"
"    IMSZ : input int\n"
"    MEM : input rank-1 array('f') with bounds (*)\n"
"    WT : input rank-1 array('f') with bounds (*)\n"
"    GCH : input rank-1 array('f') with bounds (*)\n"
"    CHISQ : input float";
/* extern void F_FUNC(MEMONEIT,MEMONEIT)(int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,cb_CALGCH_in_MEMONEIT__user__routines_typedef); */
static PyObject *f2py_rout_memsubs_MEMONEIT(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,cb_CALGCH_in_MEMONEIT__user__routines_typedef)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int DOINIT = 0;
  PyObject *DOINIT_capi = Py_None;
  int IMSZ = 0;
  PyObject *IMSZ_capi = Py_None;
  float *MEM = NULL;
  npy_intp MEM_Dims[1] = {-1};
  const int MEM_Rank = 1;
  PyArrayObject *capi_MEM_tmp = NULL;
  int capi_MEM_intent = 0;
  PyObject *MEM_capi = Py_None;
  float *DEF = NULL;
  npy_intp DEF_Dims[1] = {-1};
  const int DEF_Rank = 1;
  PyArrayObject *capi_DEF_tmp = NULL;
  int capi_DEF_intent = 0;
  PyObject *DEF_capi = Py_None;
  float DEFLEV = 0;
  PyObject *DEFLEV_capi = Py_None;
  float *STP = NULL;
  npy_intp STP_Dims[1] = {-1};
  const int STP_Rank = 1;
  PyArrayObject *capi_STP_tmp = NULL;
  int capi_STP_intent = 0;
  PyObject *STP_capi = Py_None;
  float *GCH = NULL;
  npy_intp GCH_Dims[1] = {-1};
  const int GCH_Rank = 1;
  PyArrayObject *capi_GCH_tmp = NULL;
  int capi_GCH_intent = 0;
  PyObject *GCH_capi = Py_None;
  float *WT = NULL;
  npy_intp WT_Dims[1] = {-1};
  const int WT_Rank = 1;
  PyArrayObject *capi_WT_tmp = NULL;
  int capi_WT_intent = 0;
  PyObject *WT_capi = Py_None;
  float Q = 0;
  PyObject *Q_capi = Py_None;
  float TFLUX = 0;
  PyObject *TFLUX_capi = Py_None;
  float TCHISQ = 0;
  PyObject *TCHISQ_capi = Py_None;
  float TOL = 0;
  PyObject *TOL_capi = Py_None;
  float FLUX = 0;
  PyObject *FLUX_capi = Py_None;
  float CHISQ = 0;
  PyObject *CHISQ_capi = Py_None;
  float ENTRPY = 0;
  PyObject *ENTRPY_capi = Py_None;
  float NRMGRD = 0;
  PyObject *NRMGRD_capi = Py_None;
  PyObject *CALGCH_capi = Py_None;
  PyTupleObject *CALGCH_xa_capi = NULL;
  PyTupleObject *CALGCH_args_capi = NULL;
  int CALGCH_nofargs_capi = 0;
  cb_CALGCH_in_MEMONEIT__user__routines_typedef CALGCH_cptr;
  static char *capi_kwlist[] = {"DOINIT","IMSZ","MEM","DEF","DEFLEV","STP","GCH","WT","Q","TFLUX","TCHISQ","TOL","FLUX","CHISQ","ENTRPY","NRMGRD","CALGCH","CALGCH_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOO|O!:memsubs.MEMONEIT",\
    capi_kwlist,&DOINIT_capi,&IMSZ_capi,&MEM_capi,&DEF_capi,&DEFLEV_capi,&STP_capi,&GCH_capi,&WT_capi,&Q_capi,&TFLUX_capi,&TCHISQ_capi,&TOL_capi,&FLUX_capi,&CHISQ_capi,&ENTRPY_capi,&NRMGRD_capi,&CALGCH_capi,&PyTuple_Type,&CALGCH_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable DEFLEV */
    f2py_success = float_from_pyobj(&DEFLEV,DEFLEV_capi,"memsubs.MEMONEIT() 5th argument (DEFLEV) can't be converted to float");
  if (f2py_success) {
  /* Processing variable WT */
  ;
  capi_WT_intent |= F2PY_INTENT_IN;
  capi_WT_tmp = array_from_pyobj(PyArray_FLOAT,WT_Dims,WT_Rank,capi_WT_intent,WT_capi);
  if (capi_WT_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 8th argument `WT' of memsubs.MEMONEIT to C/Fortran array" );
  } else {
    WT = (float *)(capi_WT_tmp->data);

  /* Processing variable TOL */
    f2py_success = float_from_pyobj(&TOL,TOL_capi,"memsubs.MEMONEIT() 12nd argument (TOL) can't be converted to float");
  if (f2py_success) {
  /* Processing variable CALGCH */
if(PyCObject_Check(CALGCH_capi)) {
  CALGCH_cptr = PyCObject_AsVoidPtr(CALGCH_capi);
} else {
  CALGCH_cptr = cb_CALGCH_in_MEMONEIT__user__routines;
}

  CALGCH_nofargs_capi = cb_CALGCH_in_MEMONEIT__user__routines_nofargs;
  if (create_cb_arglist(CALGCH_capi,CALGCH_xa_capi,5,0,&cb_CALGCH_in_MEMONEIT__user__routines_nofargs,&CALGCH_args_capi,"failed in processing argument list for call-back CALGCH.")) {
    jmp_buf CALGCH_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `CALGCH`.\n");
    SWAP(CALGCH_capi,cb_CALGCH_in_MEMONEIT__user__routines_capi,PyObject);
    SWAP(CALGCH_args_capi,cb_CALGCH_in_MEMONEIT__user__routines_args_capi,PyTupleObject);
    memcpy(&CALGCH_jmpbuf,&cb_CALGCH_in_MEMONEIT__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable DEF */
  ;
  capi_DEF_intent |= F2PY_INTENT_IN;
  capi_DEF_tmp = array_from_pyobj(PyArray_FLOAT,DEF_Dims,DEF_Rank,capi_DEF_intent,DEF_capi);
  if (capi_DEF_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 4th argument `DEF' of memsubs.MEMONEIT to C/Fortran array" );
  } else {
    DEF = (float *)(capi_DEF_tmp->data);

  /* Processing variable TCHISQ */
    f2py_success = float_from_pyobj(&TCHISQ,TCHISQ_capi,"memsubs.MEMONEIT() 11st argument (TCHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable FLUX */
    f2py_success = float_from_pyobj(&FLUX,FLUX_capi,"memsubs.MEMONEIT() 13rd argument (FLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable CHISQ */
    f2py_success = float_from_pyobj(&CHISQ,CHISQ_capi,"memsubs.MEMONEIT() 14th argument (CHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable NRMGRD */
    f2py_success = float_from_pyobj(&NRMGRD,NRMGRD_capi,"memsubs.MEMONEIT() 16th argument (NRMGRD) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ENTRPY */
    f2py_success = float_from_pyobj(&ENTRPY,ENTRPY_capi,"memsubs.MEMONEIT() 15th argument (ENTRPY) can't be converted to float");
  if (f2py_success) {
  /* Processing variable TFLUX */
    f2py_success = float_from_pyobj(&TFLUX,TFLUX_capi,"memsubs.MEMONEIT() 10th argument (TFLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GCH */
  ;
  capi_GCH_intent |= F2PY_INTENT_IN;
  capi_GCH_tmp = array_from_pyobj(PyArray_FLOAT,GCH_Dims,GCH_Rank,capi_GCH_intent,GCH_capi);
  if (capi_GCH_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 7th argument `GCH' of memsubs.MEMONEIT to C/Fortran array" );
  } else {
    GCH = (float *)(capi_GCH_tmp->data);

  /* Processing variable Q */
    f2py_success = float_from_pyobj(&Q,Q_capi,"memsubs.MEMONEIT() 9th argument (Q) can't be converted to float");
  if (f2py_success) {
  /* Processing variable STP */
  ;
  capi_STP_intent |= F2PY_INTENT_IN;
  capi_STP_tmp = array_from_pyobj(PyArray_FLOAT,STP_Dims,STP_Rank,capi_STP_intent,STP_capi);
  if (capi_STP_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 6th argument `STP' of memsubs.MEMONEIT to C/Fortran array" );
  } else {
    STP = (float *)(capi_STP_tmp->data);

  /* Processing variable MEM */
  ;
  capi_MEM_intent |= F2PY_INTENT_IN;
  capi_MEM_tmp = array_from_pyobj(PyArray_FLOAT,MEM_Dims,MEM_Rank,capi_MEM_intent,MEM_capi);
  if (capi_MEM_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 3rd argument `MEM' of memsubs.MEMONEIT to C/Fortran array" );
  } else {
    MEM = (float *)(capi_MEM_tmp->data);

  /* Processing variable IMSZ */
    f2py_success = int_from_pyobj(&IMSZ,IMSZ_capi,"memsubs.MEMONEIT() 2nd argument (IMSZ) can't be converted to int");
  if (f2py_success) {
  /* Processing variable DOINIT */
    DOINIT = (int)PyObject_IsTrue(DOINIT_capi);
    f2py_success = 1;
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_CALGCH_in_MEMONEIT__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&DOINIT,&IMSZ,MEM,DEF,&DEFLEV,STP,GCH,WT,&Q,&TFLUX,&TCHISQ,&TOL,&FLUX,&CHISQ,&ENTRPY,&NRMGRD,CALGCH_cptr);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of DOINIT*/
  /* End of cleaning variable DOINIT */
  } /*if (f2py_success) of IMSZ*/
  /* End of cleaning variable IMSZ */
  if((PyObject *)capi_MEM_tmp!=MEM_capi) {
    Py_XDECREF(capi_MEM_tmp); }
  }  /*if (capi_MEM_tmp == NULL) ... else of MEM*/
  /* End of cleaning variable MEM */
  if((PyObject *)capi_STP_tmp!=STP_capi) {
    Py_XDECREF(capi_STP_tmp); }
  }  /*if (capi_STP_tmp == NULL) ... else of STP*/
  /* End of cleaning variable STP */
  } /*if (f2py_success) of Q*/
  /* End of cleaning variable Q */
  if((PyObject *)capi_GCH_tmp!=GCH_capi) {
    Py_XDECREF(capi_GCH_tmp); }
  }  /*if (capi_GCH_tmp == NULL) ... else of GCH*/
  /* End of cleaning variable GCH */
  } /*if (f2py_success) of TFLUX*/
  /* End of cleaning variable TFLUX */
  } /*if (f2py_success) of ENTRPY*/
  /* End of cleaning variable ENTRPY */
  } /*if (f2py_success) of NRMGRD*/
  /* End of cleaning variable NRMGRD */
  } /*if (f2py_success) of CHISQ*/
  /* End of cleaning variable CHISQ */
  } /*if (f2py_success) of FLUX*/
  /* End of cleaning variable FLUX */
  } /*if (f2py_success) of TCHISQ*/
  /* End of cleaning variable TCHISQ */
  if((PyObject *)capi_DEF_tmp!=DEF_capi) {
    Py_XDECREF(capi_DEF_tmp); }
  }  /*if (capi_DEF_tmp == NULL) ... else of DEF*/
  /* End of cleaning variable DEF */
    CFUNCSMESS("Restoring jmpbuf for `CALGCH`.\n");
    cb_CALGCH_in_MEMONEIT__user__routines_capi = CALGCH_capi;
    Py_DECREF(cb_CALGCH_in_MEMONEIT__user__routines_args_capi);
    cb_CALGCH_in_MEMONEIT__user__routines_args_capi = CALGCH_args_capi;
    cb_CALGCH_in_MEMONEIT__user__routines_nofargs = CALGCH_nofargs_capi;
    memcpy(&cb_CALGCH_in_MEMONEIT__user__routines_jmpbuf,&CALGCH_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable CALGCH */
  } /*if (f2py_success) of TOL*/
  /* End of cleaning variable TOL */
  if((PyObject *)capi_WT_tmp!=WT_capi) {
    Py_XDECREF(capi_WT_tmp); }
  }  /*if (capi_WT_tmp == NULL) ... else of WT*/
  /* End of cleaning variable WT */
  } /*if (f2py_success) of DEFLEV*/
  /* End of cleaning variable DEFLEV */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMONEIT ******************************/

/********************************** MEMCALHF **********************************/
static char doc_f2py_rout_memsubs_MEMCALHF[] = "\
Function signature:\n\
  MEMCALHF(IMSZ,IN1,IN2,DEFLEV,FLUX,ENTRPY)\n\
Required arguments:\n"
"  IMSZ : input int\n"
"  IN1 : input rank-1 array('f') with bounds (*)\n"
"  IN2 : input rank-1 array('f') with bounds (*)\n"
"  DEFLEV : input float\n"
"  FLUX : input float\n"
"  ENTRPY : input float";
/* extern void F_FUNC(MEMCALHF,MEMCALHF)(int*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_memsubs_MEMCALHF(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int IMSZ = 0;
  PyObject *IMSZ_capi = Py_None;
  float *IN1 = NULL;
  npy_intp IN1_Dims[1] = {-1};
  const int IN1_Rank = 1;
  PyArrayObject *capi_IN1_tmp = NULL;
  int capi_IN1_intent = 0;
  PyObject *IN1_capi = Py_None;
  float *IN2 = NULL;
  npy_intp IN2_Dims[1] = {-1};
  const int IN2_Rank = 1;
  PyArrayObject *capi_IN2_tmp = NULL;
  int capi_IN2_intent = 0;
  PyObject *IN2_capi = Py_None;
  float DEFLEV = 0;
  PyObject *DEFLEV_capi = Py_None;
  float FLUX = 0;
  PyObject *FLUX_capi = Py_None;
  float ENTRPY = 0;
  PyObject *ENTRPY_capi = Py_None;
  static char *capi_kwlist[] = {"IMSZ","IN1","IN2","DEFLEV","FLUX","ENTRPY",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:memsubs.MEMCALHF",\
    capi_kwlist,&IMSZ_capi,&IN1_capi,&IN2_capi,&DEFLEV_capi,&FLUX_capi,&ENTRPY_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ENTRPY */
    f2py_success = float_from_pyobj(&ENTRPY,ENTRPY_capi,"memsubs.MEMCALHF() 6th argument (ENTRPY) can't be converted to float");
  if (f2py_success) {
  /* Processing variable FLUX */
    f2py_success = float_from_pyobj(&FLUX,FLUX_capi,"memsubs.MEMCALHF() 5th argument (FLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable DEFLEV */
    f2py_success = float_from_pyobj(&DEFLEV,DEFLEV_capi,"memsubs.MEMCALHF() 4th argument (DEFLEV) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IMSZ */
    f2py_success = int_from_pyobj(&IMSZ,IMSZ_capi,"memsubs.MEMCALHF() 1st argument (IMSZ) can't be converted to int");
  if (f2py_success) {
  /* Processing variable IN2 */
  ;
  capi_IN2_intent |= F2PY_INTENT_IN;
  capi_IN2_tmp = array_from_pyobj(PyArray_FLOAT,IN2_Dims,IN2_Rank,capi_IN2_intent,IN2_capi);
  if (capi_IN2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 3rd argument `IN2' of memsubs.MEMCALHF to C/Fortran array" );
  } else {
    IN2 = (float *)(capi_IN2_tmp->data);

  /* Processing variable IN1 */
  ;
  capi_IN1_intent |= F2PY_INTENT_IN;
  capi_IN1_tmp = array_from_pyobj(PyArray_FLOAT,IN1_Dims,IN1_Rank,capi_IN1_intent,IN1_capi);
  if (capi_IN1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 2nd argument `IN1' of memsubs.MEMCALHF to C/Fortran array" );
  } else {
    IN1 = (float *)(capi_IN1_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&IMSZ,IN1,IN2,&DEFLEV,&FLUX,&ENTRPY);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_IN1_tmp!=IN1_capi) {
    Py_XDECREF(capi_IN1_tmp); }
  }  /*if (capi_IN1_tmp == NULL) ... else of IN1*/
  /* End of cleaning variable IN1 */
  if((PyObject *)capi_IN2_tmp!=IN2_capi) {
    Py_XDECREF(capi_IN2_tmp); }
  }  /*if (capi_IN2_tmp == NULL) ... else of IN2*/
  /* End of cleaning variable IN2 */
  } /*if (f2py_success) of IMSZ*/
  /* End of cleaning variable IMSZ */
  } /*if (f2py_success) of DEFLEV*/
  /* End of cleaning variable DEFLEV */
  } /*if (f2py_success) of FLUX*/
  /* End of cleaning variable FLUX */
  } /*if (f2py_success) of ENTRPY*/
  /* End of cleaning variable ENTRPY */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMCALHF ******************************/

/********************************** MEMCHALB **********************************/
static char doc_f2py_rout_memsubs_MEMCHALB[] = "\
Function signature:\n\
  MEMCHALB(IMSZ,MEM,DEF,DEFLEV,GCH,WT,ALPHA,BETA,Q,FLUX,TFLUX,CHISQ,TCHISQ,TOL,NRMGRD,GDG)\n\
Required arguments:\n"
"  IMSZ : input int\n"
"  MEM : input rank-1 array('f') with bounds (*)\n"
"  DEF : input rank-1 array('f') with bounds (*)\n"
"  DEFLEV : input float\n"
"  GCH : input rank-1 array('f') with bounds (*)\n"
"  WT : input rank-1 array('f') with bounds (*)\n"
"  ALPHA : input float\n"
"  BETA : input float\n"
"  Q : input float\n"
"  FLUX : input float\n"
"  TFLUX : input float\n"
"  CHISQ : input float\n"
"  TCHISQ : input float\n"
"  TOL : input float\n"
"  NRMGRD : input float\n"
"  GDG : input rank-2 array('d') with bounds (4,4)";
/* extern void F_FUNC(MEMCHALB,MEMCHALB)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*); */
static PyObject *f2py_rout_memsubs_MEMCHALB(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int IMSZ = 0;
  PyObject *IMSZ_capi = Py_None;
  float *MEM = NULL;
  npy_intp MEM_Dims[1] = {-1};
  const int MEM_Rank = 1;
  PyArrayObject *capi_MEM_tmp = NULL;
  int capi_MEM_intent = 0;
  PyObject *MEM_capi = Py_None;
  float *DEF = NULL;
  npy_intp DEF_Dims[1] = {-1};
  const int DEF_Rank = 1;
  PyArrayObject *capi_DEF_tmp = NULL;
  int capi_DEF_intent = 0;
  PyObject *DEF_capi = Py_None;
  float DEFLEV = 0;
  PyObject *DEFLEV_capi = Py_None;
  float *GCH = NULL;
  npy_intp GCH_Dims[1] = {-1};
  const int GCH_Rank = 1;
  PyArrayObject *capi_GCH_tmp = NULL;
  int capi_GCH_intent = 0;
  PyObject *GCH_capi = Py_None;
  float *WT = NULL;
  npy_intp WT_Dims[1] = {-1};
  const int WT_Rank = 1;
  PyArrayObject *capi_WT_tmp = NULL;
  int capi_WT_intent = 0;
  PyObject *WT_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float BETA = 0;
  PyObject *BETA_capi = Py_None;
  float Q = 0;
  PyObject *Q_capi = Py_None;
  float FLUX = 0;
  PyObject *FLUX_capi = Py_None;
  float TFLUX = 0;
  PyObject *TFLUX_capi = Py_None;
  float CHISQ = 0;
  PyObject *CHISQ_capi = Py_None;
  float TCHISQ = 0;
  PyObject *TCHISQ_capi = Py_None;
  float TOL = 0;
  PyObject *TOL_capi = Py_None;
  float NRMGRD = 0;
  PyObject *NRMGRD_capi = Py_None;
  double *GDG = NULL;
  npy_intp GDG_Dims[2] = {-1, -1};
  const int GDG_Rank = 2;
  PyArrayObject *capi_GDG_tmp = NULL;
  int capi_GDG_intent = 0;
  PyObject *GDG_capi = Py_None;
  static char *capi_kwlist[] = {"IMSZ","MEM","DEF","DEFLEV","GCH","WT","ALPHA","BETA","Q","FLUX","TFLUX","CHISQ","TCHISQ","TOL","NRMGRD","GDG",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|:memsubs.MEMCHALB",\
    capi_kwlist,&IMSZ_capi,&MEM_capi,&DEF_capi,&DEFLEV_capi,&GCH_capi,&WT_capi,&ALPHA_capi,&BETA_capi,&Q_capi,&FLUX_capi,&TFLUX_capi,&CHISQ_capi,&TCHISQ_capi,&TOL_capi,&NRMGRD_capi,&GDG_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable TFLUX */
    f2py_success = float_from_pyobj(&TFLUX,TFLUX_capi,"memsubs.MEMCHALB() 11st argument (TFLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Q */
    f2py_success = float_from_pyobj(&Q,Q_capi,"memsubs.MEMCHALB() 9th argument (Q) can't be converted to float");
  if (f2py_success) {
  /* Processing variable BETA */
    f2py_success = float_from_pyobj(&BETA,BETA_capi,"memsubs.MEMCHALB() 8th argument (BETA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable WT */
  ;
  capi_WT_intent |= F2PY_INTENT_IN;
  capi_WT_tmp = array_from_pyobj(PyArray_FLOAT,WT_Dims,WT_Rank,capi_WT_intent,WT_capi);
  if (capi_WT_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 6th argument `WT' of memsubs.MEMCHALB to C/Fortran array" );
  } else {
    WT = (float *)(capi_WT_tmp->data);

  /* Processing variable TOL */
    f2py_success = float_from_pyobj(&TOL,TOL_capi,"memsubs.MEMCHALB() 14th argument (TOL) can't be converted to float");
  if (f2py_success) {
  /* Processing variable DEF */
  ;
  capi_DEF_intent |= F2PY_INTENT_IN;
  capi_DEF_tmp = array_from_pyobj(PyArray_FLOAT,DEF_Dims,DEF_Rank,capi_DEF_intent,DEF_capi);
  if (capi_DEF_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 3rd argument `DEF' of memsubs.MEMCHALB to C/Fortran array" );
  } else {
    DEF = (float *)(capi_DEF_tmp->data);

  /* Processing variable TCHISQ */
    f2py_success = float_from_pyobj(&TCHISQ,TCHISQ_capi,"memsubs.MEMCHALB() 13rd argument (TCHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable MEM */
  ;
  capi_MEM_intent |= F2PY_INTENT_IN;
  capi_MEM_tmp = array_from_pyobj(PyArray_FLOAT,MEM_Dims,MEM_Rank,capi_MEM_intent,MEM_capi);
  if (capi_MEM_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 2nd argument `MEM' of memsubs.MEMCHALB to C/Fortran array" );
  } else {
    MEM = (float *)(capi_MEM_tmp->data);

  /* Processing variable GDG */
  GDG_Dims[0]=4,GDG_Dims[1]=4;
  capi_GDG_intent |= F2PY_INTENT_IN;
  capi_GDG_tmp = array_from_pyobj(PyArray_DOUBLE,GDG_Dims,GDG_Rank,capi_GDG_intent,GDG_capi);
  if (capi_GDG_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 16th argument `GDG' of memsubs.MEMCHALB to C/Fortran array" );
  } else {
    GDG = (double *)(capi_GDG_tmp->data);

  /* Processing variable DEFLEV */
    f2py_success = float_from_pyobj(&DEFLEV,DEFLEV_capi,"memsubs.MEMCHALB() 4th argument (DEFLEV) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IMSZ */
    f2py_success = int_from_pyobj(&IMSZ,IMSZ_capi,"memsubs.MEMCHALB() 1st argument (IMSZ) can't be converted to int");
  if (f2py_success) {
  /* Processing variable FLUX */
    f2py_success = float_from_pyobj(&FLUX,FLUX_capi,"memsubs.MEMCHALB() 10th argument (FLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable CHISQ */
    f2py_success = float_from_pyobj(&CHISQ,CHISQ_capi,"memsubs.MEMCHALB() 12nd argument (CHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GCH */
  ;
  capi_GCH_intent |= F2PY_INTENT_IN;
  capi_GCH_tmp = array_from_pyobj(PyArray_FLOAT,GCH_Dims,GCH_Rank,capi_GCH_intent,GCH_capi);
  if (capi_GCH_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 5th argument `GCH' of memsubs.MEMCHALB to C/Fortran array" );
  } else {
    GCH = (float *)(capi_GCH_tmp->data);

  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"memsubs.MEMCHALB() 7th argument (ALPHA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable NRMGRD */
    f2py_success = float_from_pyobj(&NRMGRD,NRMGRD_capi,"memsubs.MEMCHALB() 15th argument (NRMGRD) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&IMSZ,MEM,DEF,&DEFLEV,GCH,WT,&ALPHA,&BETA,&Q,&FLUX,&TFLUX,&CHISQ,&TCHISQ,&TOL,&NRMGRD,GDG);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of NRMGRD*/
  /* End of cleaning variable NRMGRD */
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  if((PyObject *)capi_GCH_tmp!=GCH_capi) {
    Py_XDECREF(capi_GCH_tmp); }
  }  /*if (capi_GCH_tmp == NULL) ... else of GCH*/
  /* End of cleaning variable GCH */
  } /*if (f2py_success) of CHISQ*/
  /* End of cleaning variable CHISQ */
  } /*if (f2py_success) of FLUX*/
  /* End of cleaning variable FLUX */
  } /*if (f2py_success) of IMSZ*/
  /* End of cleaning variable IMSZ */
  } /*if (f2py_success) of DEFLEV*/
  /* End of cleaning variable DEFLEV */
  if((PyObject *)capi_GDG_tmp!=GDG_capi) {
    Py_XDECREF(capi_GDG_tmp); }
  }  /*if (capi_GDG_tmp == NULL) ... else of GDG*/
  /* End of cleaning variable GDG */
  if((PyObject *)capi_MEM_tmp!=MEM_capi) {
    Py_XDECREF(capi_MEM_tmp); }
  }  /*if (capi_MEM_tmp == NULL) ... else of MEM*/
  /* End of cleaning variable MEM */
  } /*if (f2py_success) of TCHISQ*/
  /* End of cleaning variable TCHISQ */
  if((PyObject *)capi_DEF_tmp!=DEF_capi) {
    Py_XDECREF(capi_DEF_tmp); }
  }  /*if (capi_DEF_tmp == NULL) ... else of DEF*/
  /* End of cleaning variable DEF */
  } /*if (f2py_success) of TOL*/
  /* End of cleaning variable TOL */
  if((PyObject *)capi_WT_tmp!=WT_capi) {
    Py_XDECREF(capi_WT_tmp); }
  }  /*if (capi_WT_tmp == NULL) ... else of WT*/
  /* End of cleaning variable WT */
  } /*if (f2py_success) of BETA*/
  /* End of cleaning variable BETA */
  } /*if (f2py_success) of Q*/
  /* End of cleaning variable Q */
  } /*if (f2py_success) of TFLUX*/
  /* End of cleaning variable TFLUX */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMCHALB ******************************/

/********************************** MEMCLSTP **********************************/
static char doc_f2py_rout_memsubs_MEMCLSTP[] = "\
Function signature:\n\
  MEMCLSTP(IMSZ,MEM,DEF,DEFLEV,STP,GCH,WT,ALPHA,BETA,Q,FLUX,IMMAX,IMMIN,NRMGRD,GDG,GDSTEP)\n\
Required arguments:\n"
"  IMSZ : input int\n"
"  MEM : input rank-1 array('f') with bounds (*)\n"
"  DEF : input rank-1 array('f') with bounds (*)\n"
"  DEFLEV : input float\n"
"  STP : input rank-1 array('f') with bounds (*)\n"
"  GCH : input rank-1 array('f') with bounds (*)\n"
"  WT : input rank-1 array('f') with bounds (*)\n"
"  ALPHA : input float\n"
"  BETA : input float\n"
"  Q : input float\n"
"  FLUX : input float\n"
"  IMMAX : input float\n"
"  IMMIN : input float\n"
"  NRMGRD : input float\n"
"  GDG : input rank-2 array('d') with bounds (4,4)\n"
"  GDSTEP : input float";
/* extern void F_FUNC(MEMCLSTP,MEMCLSTP)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*,float*); */
static PyObject *f2py_rout_memsubs_MEMCLSTP(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,double*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int IMSZ = 0;
  PyObject *IMSZ_capi = Py_None;
  float *MEM = NULL;
  npy_intp MEM_Dims[1] = {-1};
  const int MEM_Rank = 1;
  PyArrayObject *capi_MEM_tmp = NULL;
  int capi_MEM_intent = 0;
  PyObject *MEM_capi = Py_None;
  float *DEF = NULL;
  npy_intp DEF_Dims[1] = {-1};
  const int DEF_Rank = 1;
  PyArrayObject *capi_DEF_tmp = NULL;
  int capi_DEF_intent = 0;
  PyObject *DEF_capi = Py_None;
  float DEFLEV = 0;
  PyObject *DEFLEV_capi = Py_None;
  float *STP = NULL;
  npy_intp STP_Dims[1] = {-1};
  const int STP_Rank = 1;
  PyArrayObject *capi_STP_tmp = NULL;
  int capi_STP_intent = 0;
  PyObject *STP_capi = Py_None;
  float *GCH = NULL;
  npy_intp GCH_Dims[1] = {-1};
  const int GCH_Rank = 1;
  PyArrayObject *capi_GCH_tmp = NULL;
  int capi_GCH_intent = 0;
  PyObject *GCH_capi = Py_None;
  float *WT = NULL;
  npy_intp WT_Dims[1] = {-1};
  const int WT_Rank = 1;
  PyArrayObject *capi_WT_tmp = NULL;
  int capi_WT_intent = 0;
  PyObject *WT_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float BETA = 0;
  PyObject *BETA_capi = Py_None;
  float Q = 0;
  PyObject *Q_capi = Py_None;
  float FLUX = 0;
  PyObject *FLUX_capi = Py_None;
  float IMMAX = 0;
  PyObject *IMMAX_capi = Py_None;
  float IMMIN = 0;
  PyObject *IMMIN_capi = Py_None;
  float NRMGRD = 0;
  PyObject *NRMGRD_capi = Py_None;
  double *GDG = NULL;
  npy_intp GDG_Dims[2] = {-1, -1};
  const int GDG_Rank = 2;
  PyArrayObject *capi_GDG_tmp = NULL;
  int capi_GDG_intent = 0;
  PyObject *GDG_capi = Py_None;
  float GDSTEP = 0;
  PyObject *GDSTEP_capi = Py_None;
  static char *capi_kwlist[] = {"IMSZ","MEM","DEF","DEFLEV","STP","GCH","WT","ALPHA","BETA","Q","FLUX","IMMAX","IMMIN","NRMGRD","GDG","GDSTEP",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOO|:memsubs.MEMCLSTP",\
    capi_kwlist,&IMSZ_capi,&MEM_capi,&DEF_capi,&DEFLEV_capi,&STP_capi,&GCH_capi,&WT_capi,&ALPHA_capi,&BETA_capi,&Q_capi,&FLUX_capi,&IMMAX_capi,&IMMIN_capi,&NRMGRD_capi,&GDG_capi,&GDSTEP_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable Q */
    f2py_success = float_from_pyobj(&Q,Q_capi,"memsubs.MEMCLSTP() 10th argument (Q) can't be converted to float");
  if (f2py_success) {
  /* Processing variable BETA */
    f2py_success = float_from_pyobj(&BETA,BETA_capi,"memsubs.MEMCLSTP() 9th argument (BETA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable WT */
  ;
  capi_WT_intent |= F2PY_INTENT_IN;
  capi_WT_tmp = array_from_pyobj(PyArray_FLOAT,WT_Dims,WT_Rank,capi_WT_intent,WT_capi);
  if (capi_WT_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 7th argument `WT' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    WT = (float *)(capi_WT_tmp->data);

  /* Processing variable STP */
  ;
  capi_STP_intent |= F2PY_INTENT_IN;
  capi_STP_tmp = array_from_pyobj(PyArray_FLOAT,STP_Dims,STP_Rank,capi_STP_intent,STP_capi);
  if (capi_STP_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 5th argument `STP' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    STP = (float *)(capi_STP_tmp->data);

  /* Processing variable IMMAX */
    f2py_success = float_from_pyobj(&IMMAX,IMMAX_capi,"memsubs.MEMCLSTP() 12nd argument (IMMAX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GDSTEP */
    f2py_success = float_from_pyobj(&GDSTEP,GDSTEP_capi,"memsubs.MEMCLSTP() 16th argument (GDSTEP) can't be converted to float");
  if (f2py_success) {
  /* Processing variable DEF */
  ;
  capi_DEF_intent |= F2PY_INTENT_IN;
  capi_DEF_tmp = array_from_pyobj(PyArray_FLOAT,DEF_Dims,DEF_Rank,capi_DEF_intent,DEF_capi);
  if (capi_DEF_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 3rd argument `DEF' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    DEF = (float *)(capi_DEF_tmp->data);

  /* Processing variable IMMIN */
    f2py_success = float_from_pyobj(&IMMIN,IMMIN_capi,"memsubs.MEMCLSTP() 13rd argument (IMMIN) can't be converted to float");
  if (f2py_success) {
  /* Processing variable MEM */
  ;
  capi_MEM_intent |= F2PY_INTENT_IN;
  capi_MEM_tmp = array_from_pyobj(PyArray_FLOAT,MEM_Dims,MEM_Rank,capi_MEM_intent,MEM_capi);
  if (capi_MEM_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 2nd argument `MEM' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    MEM = (float *)(capi_MEM_tmp->data);

  /* Processing variable DEFLEV */
    f2py_success = float_from_pyobj(&DEFLEV,DEFLEV_capi,"memsubs.MEMCLSTP() 4th argument (DEFLEV) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IMSZ */
    f2py_success = int_from_pyobj(&IMSZ,IMSZ_capi,"memsubs.MEMCLSTP() 1st argument (IMSZ) can't be converted to int");
  if (f2py_success) {
  /* Processing variable FLUX */
    f2py_success = float_from_pyobj(&FLUX,FLUX_capi,"memsubs.MEMCLSTP() 11st argument (FLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GDG */
  GDG_Dims[0]=4,GDG_Dims[1]=4;
  capi_GDG_intent |= F2PY_INTENT_IN;
  capi_GDG_tmp = array_from_pyobj(PyArray_DOUBLE,GDG_Dims,GDG_Rank,capi_GDG_intent,GDG_capi);
  if (capi_GDG_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 15th argument `GDG' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    GDG = (double *)(capi_GDG_tmp->data);

  /* Processing variable GCH */
  ;
  capi_GCH_intent |= F2PY_INTENT_IN;
  capi_GCH_tmp = array_from_pyobj(PyArray_FLOAT,GCH_Dims,GCH_Rank,capi_GCH_intent,GCH_capi);
  if (capi_GCH_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 6th argument `GCH' of memsubs.MEMCLSTP to C/Fortran array" );
  } else {
    GCH = (float *)(capi_GCH_tmp->data);

  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"memsubs.MEMCLSTP() 8th argument (ALPHA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable NRMGRD */
    f2py_success = float_from_pyobj(&NRMGRD,NRMGRD_capi,"memsubs.MEMCLSTP() 14th argument (NRMGRD) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&IMSZ,MEM,DEF,&DEFLEV,STP,GCH,WT,&ALPHA,&BETA,&Q,&FLUX,&IMMAX,&IMMIN,&NRMGRD,GDG,&GDSTEP);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of NRMGRD*/
  /* End of cleaning variable NRMGRD */
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  if((PyObject *)capi_GCH_tmp!=GCH_capi) {
    Py_XDECREF(capi_GCH_tmp); }
  }  /*if (capi_GCH_tmp == NULL) ... else of GCH*/
  /* End of cleaning variable GCH */
  if((PyObject *)capi_GDG_tmp!=GDG_capi) {
    Py_XDECREF(capi_GDG_tmp); }
  }  /*if (capi_GDG_tmp == NULL) ... else of GDG*/
  /* End of cleaning variable GDG */
  } /*if (f2py_success) of FLUX*/
  /* End of cleaning variable FLUX */
  } /*if (f2py_success) of IMSZ*/
  /* End of cleaning variable IMSZ */
  } /*if (f2py_success) of DEFLEV*/
  /* End of cleaning variable DEFLEV */
  if((PyObject *)capi_MEM_tmp!=MEM_capi) {
    Py_XDECREF(capi_MEM_tmp); }
  }  /*if (capi_MEM_tmp == NULL) ... else of MEM*/
  /* End of cleaning variable MEM */
  } /*if (f2py_success) of IMMIN*/
  /* End of cleaning variable IMMIN */
  if((PyObject *)capi_DEF_tmp!=DEF_capi) {
    Py_XDECREF(capi_DEF_tmp); }
  }  /*if (capi_DEF_tmp == NULL) ... else of DEF*/
  /* End of cleaning variable DEF */
  } /*if (f2py_success) of GDSTEP*/
  /* End of cleaning variable GDSTEP */
  } /*if (f2py_success) of IMMAX*/
  /* End of cleaning variable IMMAX */
  if((PyObject *)capi_STP_tmp!=STP_capi) {
    Py_XDECREF(capi_STP_tmp); }
  }  /*if (capi_STP_tmp == NULL) ... else of STP*/
  /* End of cleaning variable STP */
  if((PyObject *)capi_WT_tmp!=WT_capi) {
    Py_XDECREF(capi_WT_tmp); }
  }  /*if (capi_WT_tmp == NULL) ... else of WT*/
  /* End of cleaning variable WT */
  } /*if (f2py_success) of BETA*/
  /* End of cleaning variable BETA */
  } /*if (f2py_success) of Q*/
  /* End of cleaning variable Q */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMCLSTP ******************************/

/*********************************** MEMGDS ***********************************/
static char doc_f2py_rout_memsubs_MEMGDS[] = "\
Function signature:\n\
  MEMGDS(IMSZ,MEM,DEF,DEFLEV,STP,GCH,ALPHA,BETA,GDSTEP)\n\
Required arguments:\n"
"  IMSZ : input int\n"
"  MEM : input rank-1 array('f') with bounds (*)\n"
"  DEF : input rank-1 array('f') with bounds (*)\n"
"  DEFLEV : input float\n"
"  STP : input rank-1 array('f') with bounds (*)\n"
"  GCH : input rank-1 array('f') with bounds (*)\n"
"  ALPHA : input float\n"
"  BETA : input float\n"
"  GDSTEP : input float";
/* extern void F_FUNC(MEMGDS,MEMGDS)(int*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_memsubs_MEMGDS(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int IMSZ = 0;
  PyObject *IMSZ_capi = Py_None;
  float *MEM = NULL;
  npy_intp MEM_Dims[1] = {-1};
  const int MEM_Rank = 1;
  PyArrayObject *capi_MEM_tmp = NULL;
  int capi_MEM_intent = 0;
  PyObject *MEM_capi = Py_None;
  float *DEF = NULL;
  npy_intp DEF_Dims[1] = {-1};
  const int DEF_Rank = 1;
  PyArrayObject *capi_DEF_tmp = NULL;
  int capi_DEF_intent = 0;
  PyObject *DEF_capi = Py_None;
  float DEFLEV = 0;
  PyObject *DEFLEV_capi = Py_None;
  float *STP = NULL;
  npy_intp STP_Dims[1] = {-1};
  const int STP_Rank = 1;
  PyArrayObject *capi_STP_tmp = NULL;
  int capi_STP_intent = 0;
  PyObject *STP_capi = Py_None;
  float *GCH = NULL;
  npy_intp GCH_Dims[1] = {-1};
  const int GCH_Rank = 1;
  PyArrayObject *capi_GCH_tmp = NULL;
  int capi_GCH_intent = 0;
  PyObject *GCH_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float BETA = 0;
  PyObject *BETA_capi = Py_None;
  float GDSTEP = 0;
  PyObject *GDSTEP_capi = Py_None;
  static char *capi_kwlist[] = {"IMSZ","MEM","DEF","DEFLEV","STP","GCH","ALPHA","BETA","GDSTEP",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:memsubs.MEMGDS",\
    capi_kwlist,&IMSZ_capi,&MEM_capi,&DEF_capi,&DEFLEV_capi,&STP_capi,&GCH_capi,&ALPHA_capi,&BETA_capi,&GDSTEP_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable MEM */
  ;
  capi_MEM_intent |= F2PY_INTENT_IN;
  capi_MEM_tmp = array_from_pyobj(PyArray_FLOAT,MEM_Dims,MEM_Rank,capi_MEM_intent,MEM_capi);
  if (capi_MEM_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 2nd argument `MEM' of memsubs.MEMGDS to C/Fortran array" );
  } else {
    MEM = (float *)(capi_MEM_tmp->data);

  /* Processing variable GCH */
  ;
  capi_GCH_intent |= F2PY_INTENT_IN;
  capi_GCH_tmp = array_from_pyobj(PyArray_FLOAT,GCH_Dims,GCH_Rank,capi_GCH_intent,GCH_capi);
  if (capi_GCH_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 6th argument `GCH' of memsubs.MEMGDS to C/Fortran array" );
  } else {
    GCH = (float *)(capi_GCH_tmp->data);

  /* Processing variable DEFLEV */
    f2py_success = float_from_pyobj(&DEFLEV,DEFLEV_capi,"memsubs.MEMGDS() 4th argument (DEFLEV) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IMSZ */
    f2py_success = int_from_pyobj(&IMSZ,IMSZ_capi,"memsubs.MEMGDS() 1st argument (IMSZ) can't be converted to int");
  if (f2py_success) {
  /* Processing variable BETA */
    f2py_success = float_from_pyobj(&BETA,BETA_capi,"memsubs.MEMGDS() 8th argument (BETA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable STP */
  ;
  capi_STP_intent |= F2PY_INTENT_IN;
  capi_STP_tmp = array_from_pyobj(PyArray_FLOAT,STP_Dims,STP_Rank,capi_STP_intent,STP_capi);
  if (capi_STP_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 5th argument `STP' of memsubs.MEMGDS to C/Fortran array" );
  } else {
    STP = (float *)(capi_STP_tmp->data);

  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"memsubs.MEMGDS() 7th argument (ALPHA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GDSTEP */
    f2py_success = float_from_pyobj(&GDSTEP,GDSTEP_capi,"memsubs.MEMGDS() 9th argument (GDSTEP) can't be converted to float");
  if (f2py_success) {
  /* Processing variable DEF */
  ;
  capi_DEF_intent |= F2PY_INTENT_IN;
  capi_DEF_tmp = array_from_pyobj(PyArray_FLOAT,DEF_Dims,DEF_Rank,capi_DEF_intent,DEF_capi);
  if (capi_DEF_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 3rd argument `DEF' of memsubs.MEMGDS to C/Fortran array" );
  } else {
    DEF = (float *)(capi_DEF_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&IMSZ,MEM,DEF,&DEFLEV,STP,GCH,&ALPHA,&BETA,&GDSTEP);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_DEF_tmp!=DEF_capi) {
    Py_XDECREF(capi_DEF_tmp); }
  }  /*if (capi_DEF_tmp == NULL) ... else of DEF*/
  /* End of cleaning variable DEF */
  } /*if (f2py_success) of GDSTEP*/
  /* End of cleaning variable GDSTEP */
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  if((PyObject *)capi_STP_tmp!=STP_capi) {
    Py_XDECREF(capi_STP_tmp); }
  }  /*if (capi_STP_tmp == NULL) ... else of STP*/
  /* End of cleaning variable STP */
  } /*if (f2py_success) of BETA*/
  /* End of cleaning variable BETA */
  } /*if (f2py_success) of IMSZ*/
  /* End of cleaning variable IMSZ */
  } /*if (f2py_success) of DEFLEV*/
  /* End of cleaning variable DEFLEV */
  if((PyObject *)capi_GCH_tmp!=GCH_capi) {
    Py_XDECREF(capi_GCH_tmp); }
  }  /*if (capi_GCH_tmp == NULL) ... else of GCH*/
  /* End of cleaning variable GCH */
  if((PyObject *)capi_MEM_tmp!=MEM_capi) {
    Py_XDECREF(capi_MEM_tmp); }
  }  /*if (capi_MEM_tmp == NULL) ... else of MEM*/
  /* End of cleaning variable MEM */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of MEMGDS *******************************/

/********************************** MEMINIAB **********************************/
static char doc_f2py_rout_memsubs_MEMINIAB[] = "\
Function signature:\n\
  MEMINIAB(GDG,ALPHA,BETA,TFLUX)\n\
Required arguments:\n"
"  GDG : input rank-2 array('d') with bounds (4,4)\n"
"  ALPHA : input float\n"
"  BETA : input float\n"
"  TFLUX : input float";
/* extern void F_FUNC(MEMINIAB,MEMINIAB)(double*,float*,float*,float*); */
static PyObject *f2py_rout_memsubs_MEMINIAB(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *GDG = NULL;
  npy_intp GDG_Dims[2] = {-1, -1};
  const int GDG_Rank = 2;
  PyArrayObject *capi_GDG_tmp = NULL;
  int capi_GDG_intent = 0;
  PyObject *GDG_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float BETA = 0;
  PyObject *BETA_capi = Py_None;
  float TFLUX = 0;
  PyObject *TFLUX_capi = Py_None;
  static char *capi_kwlist[] = {"GDG","ALPHA","BETA","TFLUX",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|:memsubs.MEMINIAB",\
    capi_kwlist,&GDG_capi,&ALPHA_capi,&BETA_capi,&TFLUX_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable TFLUX */
    f2py_success = float_from_pyobj(&TFLUX,TFLUX_capi,"memsubs.MEMINIAB() 4th argument (TFLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable BETA */
    f2py_success = float_from_pyobj(&BETA,BETA_capi,"memsubs.MEMINIAB() 3rd argument (BETA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GDG */
  GDG_Dims[0]=4,GDG_Dims[1]=4;
  capi_GDG_intent |= F2PY_INTENT_IN;
  capi_GDG_tmp = array_from_pyobj(PyArray_DOUBLE,GDG_Dims,GDG_Rank,capi_GDG_intent,GDG_capi);
  if (capi_GDG_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 1st argument `GDG' of memsubs.MEMINIAB to C/Fortran array" );
  } else {
    GDG = (double *)(capi_GDG_tmp->data);

  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"memsubs.MEMINIAB() 2nd argument (ALPHA) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(GDG,&ALPHA,&BETA,&TFLUX);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  if((PyObject *)capi_GDG_tmp!=GDG_capi) {
    Py_XDECREF(capi_GDG_tmp); }
  }  /*if (capi_GDG_tmp == NULL) ... else of GDG*/
  /* End of cleaning variable GDG */
  } /*if (f2py_success) of BETA*/
  /* End of cleaning variable BETA */
  } /*if (f2py_success) of TFLUX*/
  /* End of cleaning variable TFLUX */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMINIAB ******************************/

/********************************** MEMTAKST **********************************/
static char doc_f2py_rout_memsubs_MEMTAKST[] = "\
Function signature:\n\
  MEMTAKST(IN1,IN2,WT1,WT2,IMLO,OUT,[N])\n\
Required arguments:\n"
"  IN1 : input rank-1 array('f') with bounds (N)\n"
"  IN2 : input rank-1 array('f') with bounds (N)\n"
"  WT1 : input float\n"
"  WT2 : input float\n"
"  IMLO : input float\n"
"  OUT : input rank-1 array('f') with bounds (N)\n"
"Optional arguments:\n"
"  N := len(IN1) input int";
/* extern void F_FUNC(MEMTAKST,MEMTAKST)(int*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_memsubs_MEMTAKST(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int N = 0;
  PyObject *N_capi = Py_None;
  float *IN1 = NULL;
  npy_intp IN1_Dims[1] = {-1};
  const int IN1_Rank = 1;
  PyArrayObject *capi_IN1_tmp = NULL;
  int capi_IN1_intent = 0;
  PyObject *IN1_capi = Py_None;
  float *IN2 = NULL;
  npy_intp IN2_Dims[1] = {-1};
  const int IN2_Rank = 1;
  PyArrayObject *capi_IN2_tmp = NULL;
  int capi_IN2_intent = 0;
  PyObject *IN2_capi = Py_None;
  float WT1 = 0;
  PyObject *WT1_capi = Py_None;
  float WT2 = 0;
  PyObject *WT2_capi = Py_None;
  float IMLO = 0;
  PyObject *IMLO_capi = Py_None;
  float *OUT = NULL;
  npy_intp OUT_Dims[1] = {-1};
  const int OUT_Rank = 1;
  PyArrayObject *capi_OUT_tmp = NULL;
  int capi_OUT_intent = 0;
  PyObject *OUT_capi = Py_None;
  static char *capi_kwlist[] = {"IN1","IN2","WT1","WT2","IMLO","OUT","N",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:memsubs.MEMTAKST",\
    capi_kwlist,&IN1_capi,&IN2_capi,&WT1_capi,&WT2_capi,&IMLO_capi,&OUT_capi,&N_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable WT1 */
    f2py_success = float_from_pyobj(&WT1,WT1_capi,"memsubs.MEMTAKST() 3rd argument (WT1) can't be converted to float");
  if (f2py_success) {
  /* Processing variable WT2 */
    f2py_success = float_from_pyobj(&WT2,WT2_capi,"memsubs.MEMTAKST() 4th argument (WT2) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IMLO */
    f2py_success = float_from_pyobj(&IMLO,IMLO_capi,"memsubs.MEMTAKST() 5th argument (IMLO) can't be converted to float");
  if (f2py_success) {
  /* Processing variable IN1 */
  ;
  capi_IN1_intent |= F2PY_INTENT_IN;
  capi_IN1_tmp = array_from_pyobj(PyArray_FLOAT,IN1_Dims,IN1_Rank,capi_IN1_intent,IN1_capi);
  if (capi_IN1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 1st argument `IN1' of memsubs.MEMTAKST to C/Fortran array" );
  } else {
    IN1 = (float *)(capi_IN1_tmp->data);

  /* Processing variable N */
  if (N_capi == Py_None) N = len(IN1); else
    f2py_success = int_from_pyobj(&N,N_capi,"memsubs.MEMTAKST() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(IN1)>=N,"len(IN1)>=N","1st keyword N","MEMTAKST:N=%d",N) {
  /* Processing variable OUT */
  OUT_Dims[0]=N;
  capi_OUT_intent |= F2PY_INTENT_IN;
  capi_OUT_tmp = array_from_pyobj(PyArray_FLOAT,OUT_Dims,OUT_Rank,capi_OUT_intent,OUT_capi);
  if (capi_OUT_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 6th argument `OUT' of memsubs.MEMTAKST to C/Fortran array" );
  } else {
    OUT = (float *)(capi_OUT_tmp->data);

  /* Processing variable IN2 */
  IN2_Dims[0]=N;
  capi_IN2_intent |= F2PY_INTENT_IN;
  capi_IN2_tmp = array_from_pyobj(PyArray_FLOAT,IN2_Dims,IN2_Rank,capi_IN2_intent,IN2_capi);
  if (capi_IN2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 2nd argument `IN2' of memsubs.MEMTAKST to C/Fortran array" );
  } else {
    IN2 = (float *)(capi_IN2_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&N,IN1,IN2,&WT1,&WT2,&IMLO,OUT);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_IN2_tmp!=IN2_capi) {
    Py_XDECREF(capi_IN2_tmp); }
  }  /*if (capi_IN2_tmp == NULL) ... else of IN2*/
  /* End of cleaning variable IN2 */
  if((PyObject *)capi_OUT_tmp!=OUT_capi) {
    Py_XDECREF(capi_OUT_tmp); }
  }  /*if (capi_OUT_tmp == NULL) ... else of OUT*/
  /* End of cleaning variable OUT */
  } /*CHECKSCALAR(len(IN1)>=N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  if((PyObject *)capi_IN1_tmp!=IN1_capi) {
    Py_XDECREF(capi_IN1_tmp); }
  }  /*if (capi_IN1_tmp == NULL) ... else of IN1*/
  /* End of cleaning variable IN1 */
  } /*if (f2py_success) of IMLO*/
  /* End of cleaning variable IMLO */
  } /*if (f2py_success) of WT2*/
  /* End of cleaning variable WT2 */
  } /*if (f2py_success) of WT1*/
  /* End of cleaning variable WT1 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMTAKST ******************************/

/********************************** MEMUPDAT **********************************/
static char doc_f2py_rout_memsubs_MEMUPDAT[] = "\
Function signature:\n\
  MEMUPDAT(GDG,TOL,TFLUX,TCHISQ,FLUX,CHISQ,LENGTH,ALPHA,BETA)\n\
Required arguments:\n"
"  GDG : input rank-2 array('d') with bounds (4,4)\n"
"  TOL : input float\n"
"  TFLUX : input float\n"
"  TCHISQ : input float\n"
"  FLUX : input float\n"
"  CHISQ : input float\n"
"  LENGTH : input float\n"
"  ALPHA : input float\n"
"  BETA : input float";
/* extern void F_FUNC(MEMUPDAT,MEMUPDAT)(double*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_memsubs_MEMUPDAT(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *GDG = NULL;
  npy_intp GDG_Dims[2] = {-1, -1};
  const int GDG_Rank = 2;
  PyArrayObject *capi_GDG_tmp = NULL;
  int capi_GDG_intent = 0;
  PyObject *GDG_capi = Py_None;
  float TOL = 0;
  PyObject *TOL_capi = Py_None;
  float TFLUX = 0;
  PyObject *TFLUX_capi = Py_None;
  float TCHISQ = 0;
  PyObject *TCHISQ_capi = Py_None;
  float FLUX = 0;
  PyObject *FLUX_capi = Py_None;
  float CHISQ = 0;
  PyObject *CHISQ_capi = Py_None;
  float LENGTH = 0;
  PyObject *LENGTH_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float BETA = 0;
  PyObject *BETA_capi = Py_None;
  static char *capi_kwlist[] = {"GDG","TOL","TFLUX","TCHISQ","FLUX","CHISQ","LENGTH","ALPHA","BETA",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:memsubs.MEMUPDAT",\
    capi_kwlist,&GDG_capi,&TOL_capi,&TFLUX_capi,&TCHISQ_capi,&FLUX_capi,&CHISQ_capi,&LENGTH_capi,&ALPHA_capi,&BETA_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable TFLUX */
    f2py_success = float_from_pyobj(&TFLUX,TFLUX_capi,"memsubs.MEMUPDAT() 3rd argument (TFLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable BETA */
    f2py_success = float_from_pyobj(&BETA,BETA_capi,"memsubs.MEMUPDAT() 9th argument (BETA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable TOL */
    f2py_success = float_from_pyobj(&TOL,TOL_capi,"memsubs.MEMUPDAT() 2nd argument (TOL) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"memsubs.MEMUPDAT() 8th argument (ALPHA) can't be converted to float");
  if (f2py_success) {
  /* Processing variable TCHISQ */
    f2py_success = float_from_pyobj(&TCHISQ,TCHISQ_capi,"memsubs.MEMUPDAT() 4th argument (TCHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable FLUX */
    f2py_success = float_from_pyobj(&FLUX,FLUX_capi,"memsubs.MEMUPDAT() 5th argument (FLUX) can't be converted to float");
  if (f2py_success) {
  /* Processing variable LENGTH */
    f2py_success = float_from_pyobj(&LENGTH,LENGTH_capi,"memsubs.MEMUPDAT() 7th argument (LENGTH) can't be converted to float");
  if (f2py_success) {
  /* Processing variable CHISQ */
    f2py_success = float_from_pyobj(&CHISQ,CHISQ_capi,"memsubs.MEMUPDAT() 6th argument (CHISQ) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GDG */
  GDG_Dims[0]=4,GDG_Dims[1]=4;
  capi_GDG_intent |= F2PY_INTENT_IN;
  capi_GDG_tmp = array_from_pyobj(PyArray_DOUBLE,GDG_Dims,GDG_Rank,capi_GDG_intent,GDG_capi);
  if (capi_GDG_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(memsubs_error,"failed in converting 1st argument `GDG' of memsubs.MEMUPDAT to C/Fortran array" );
  } else {
    GDG = (double *)(capi_GDG_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(GDG,&TOL,&TFLUX,&TCHISQ,&FLUX,&CHISQ,&LENGTH,&ALPHA,&BETA);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_GDG_tmp!=GDG_capi) {
    Py_XDECREF(capi_GDG_tmp); }
  }  /*if (capi_GDG_tmp == NULL) ... else of GDG*/
  /* End of cleaning variable GDG */
  } /*if (f2py_success) of CHISQ*/
  /* End of cleaning variable CHISQ */
  } /*if (f2py_success) of LENGTH*/
  /* End of cleaning variable LENGTH */
  } /*if (f2py_success) of FLUX*/
  /* End of cleaning variable FLUX */
  } /*if (f2py_success) of TCHISQ*/
  /* End of cleaning variable TCHISQ */
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  } /*if (f2py_success) of TOL*/
  /* End of cleaning variable TOL */
  } /*if (f2py_success) of BETA*/
  /* End of cleaning variable BETA */
  } /*if (f2py_success) of TFLUX*/
  /* End of cleaning variable TFLUX */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of MEMUPDAT ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"MEMONEIT",-1,{{-1}},0,(char *)F_FUNC(MEMONEIT,MEMONEIT),(f2py_init_func)f2py_rout_memsubs_MEMONEIT,doc_f2py_rout_memsubs_MEMONEIT},
  {"MEMCALHF",-1,{{-1}},0,(char *)F_FUNC(MEMCALHF,MEMCALHF),(f2py_init_func)f2py_rout_memsubs_MEMCALHF,doc_f2py_rout_memsubs_MEMCALHF},
  {"MEMCHALB",-1,{{-1}},0,(char *)F_FUNC(MEMCHALB,MEMCHALB),(f2py_init_func)f2py_rout_memsubs_MEMCHALB,doc_f2py_rout_memsubs_MEMCHALB},
  {"MEMCLSTP",-1,{{-1}},0,(char *)F_FUNC(MEMCLSTP,MEMCLSTP),(f2py_init_func)f2py_rout_memsubs_MEMCLSTP,doc_f2py_rout_memsubs_MEMCLSTP},
  {"MEMGDS",-1,{{-1}},0,(char *)F_FUNC(MEMGDS,MEMGDS),(f2py_init_func)f2py_rout_memsubs_MEMGDS,doc_f2py_rout_memsubs_MEMGDS},
  {"MEMINIAB",-1,{{-1}},0,(char *)F_FUNC(MEMINIAB,MEMINIAB),(f2py_init_func)f2py_rout_memsubs_MEMINIAB,doc_f2py_rout_memsubs_MEMINIAB},
  {"MEMTAKST",-1,{{-1}},0,(char *)F_FUNC(MEMTAKST,MEMTAKST),(f2py_init_func)f2py_rout_memsubs_MEMTAKST,doc_f2py_rout_memsubs_MEMTAKST},
  {"MEMUPDAT",-1,{{-1}},0,(char *)F_FUNC(MEMUPDAT,MEMUPDAT),(f2py_init_func)f2py_rout_memsubs_MEMUPDAT,doc_f2py_rout_memsubs_MEMUPDAT},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initmemsubs(void) {
  int i;
  PyObject *m,*d, *s;
  m = memsubs_module = Py_InitModule("memsubs", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred()) 
    {PyErr_SetString(PyExc_ImportError, "can't initialize module memsubs (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'memsubs' is auto-generated with f2py (version:2_3198).\nFunctions:\n"
"  MEMONEIT(DOINIT,IMSZ,MEM,DEF,DEFLEV,STP,GCH,WT,Q,TFLUX,TCHISQ,TOL,FLUX,CHISQ,ENTRPY,NRMGRD,CALGCH,CALGCH_extra_args=())\n"
"  MEMCALHF(IMSZ,IN1,IN2,DEFLEV,FLUX,ENTRPY)\n"
"  MEMCHALB(IMSZ,MEM,DEF,DEFLEV,GCH,WT,ALPHA,BETA,Q,FLUX,TFLUX,CHISQ,TCHISQ,TOL,NRMGRD,GDG)\n"
"  MEMCLSTP(IMSZ,MEM,DEF,DEFLEV,STP,GCH,WT,ALPHA,BETA,Q,FLUX,IMMAX,IMMIN,NRMGRD,GDG,GDSTEP)\n"
"  MEMGDS(IMSZ,MEM,DEF,DEFLEV,STP,GCH,ALPHA,BETA,GDSTEP)\n"
"  MEMINIAB(GDG,ALPHA,BETA,TFLUX)\n"
"  MEMTAKST(IN1,IN2,WT1,WT2,IMLO,OUT,N=len(IN1))\n"
"  MEMUPDAT(GDG,TOL,TFLUX,TCHISQ,FLUX,CHISQ,LENGTH,ALPHA,BETA)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  memsubs_error = PyErr_NewException ("memsubs.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"memsubs");
#endif

}
#ifdef __cplusplus
}
#endif
